#!/usr/bin/python

#USERNAME = 'andrei@flashsoft.ro'
#PASSWORD = 'a100a200a300'
#BASE_DOWNLOAD_PATH = 'I:/Linkedin-Learning' #use "/" as separators

USERNAME = 'andrei@flashsoft.ro'
PASSWORD = 'a100a200a300'
BASE_DOWNLOAD_PATH = 'I:/Linkedin-Learning-second' #use "/" as separators

COURSES = [
    # 'fred-kofman-on-managing-conflict',
    # 'reid-hoffman-and-chris-yeh-on-creating-an-alliance-with-employees',
    # 'bill-george-on-self-awareness-authenticity-and-leadership',
    # 'sallie-krawcheck-on-risk-taking',
    # 'betsy-corcoran-on-choosing-the-right-technology-for-your-school',
    # 'betty-liu-on-career-success',
    # 'j-t-o-donnell-on-making-recruiters-come-to-you',
    # 'gary-hamel-on-busting-bureaucracy',
    # 'shane-snow-on-storytelling',
    # 'john-maeda-on-design-business-and-inclusion',
    # 'esther-dyson-on-cultivating-health-at-scale',
    # 'influencer-interview-oprah-winfrey'
    #'node-js-testing-and-code-quality',
    #'laravel-5-essential-training-2-testing-securing-and-deploying',
    #'wordpress-developing-secure-sites',
    #'building-restful-web-apis-with-node-js-and-express',
    #'database-clinic-sqlite',
    #'angular-2-plus-creating-crud-apps',
    #'php-tips-tricks-and-techniques',
    #'vue-js-building-an-interface',
    #'learning-app-building-with-vanilla-javascript',
    #'async-programming-in-c-sharp',
    #'polyglot-web-development',
    #'ionic-3-0-for-mobile-app-developers',
    #'gdpr-compliance-essential-training',
    #'learning-java-9-modularity',
    #'learning-django',
    #'building-applications-with-angular-asp-dot-net-core-and-entity-framework-core',
    #'databases-for-node-js-developers',
    #'learning-webpack-3',
    #'node-js-real-time-web-with-socket-io',
    #'intermediate-kotlin-for-android-developers',
    #'functional-programming-with-streams-in-java-9',
    #'mastering-microservices-with-java',
    #'php-object-oriented-programming-2',
    #'microsoft-teams-bot-development',
    #'api-development-in-dot-net-with-graphql',
    #'react-working-with-apis',
    #'meteor-essential-training',
    #'vanilla-javascript-binding-and-propagation',
    #'introduction-to-data-structures-algorithms-in-java',
    #'linux-performance-tuning',
    #'python-parallel-programming-solutions',
    #'java-essential-training-objects-and-apis',
    #'learning-bash-scripting',
    #'learning-angular',
    #'python-projects',
    #'angular-building-large-applications',
    #'learning-data-visualization-with-d3-js',
    #'es6-the-right-parts',
    #'four-semesters-of-computer-science-in-5-hours',
    #'c-plus-plus-standard-template-library',
    #'learning-python-gui-programming',
    #'webpack-deep-dive',
    #'php-with-mysql-essential-training-2-build-a-cms',
    #'organizing-javascript-functionality',
    #'c-plus-plus-game-programming-1',
    #'designing-an-animated-app-ui-with-illustrator',
    #'react-native-essential-training',
    #'learning-functional-programming-with-javascript',
    #'building-a-recommendation-system-with-python-machine-learning-ai',
    #'opencv-for-python-developers',
    #'mastering-web-developer-interview-code',
    #'react-native-building-mobile-apps-3',
    #'docker-for-dot-net-developers-with-visual-studio',
    #'learning-the-owasp-top-10',
    #'building-and-deploying-deep-learning-applications-with-tensorflow',
    #'c-sharp-refactoring-tips-and-tricks',
    #'devops-foundations-continuous-delivery-continuous-integration',
    #'database-clinic-mysql',
    #'learning-c-sharp-algorithms',
    #'angular-routing',
    #'angular-progressive-web-apps',
    #'php-object-oriented-programming-with-databases',
    #'wordpress-plugin-development',
    #'c-plus-plus-game-programming-2',
    #'electronics-foundations-semiconductor-devices',
    #'learning-enterprise-web-application-performance',
    #'learning-node-js-2',
    #'learning-svg',
    #'learning-react-js-3',
    #'php-performance-optimization',
    #'css-enhancing-website-graphics',
    #'react-replacing-legacy-projects',
    #'spring-framework-in-depth',
    #'building-single-page-applications-using-asp-dot-net-core-javascriptservices',
    #'designing-restful-apis',
    #'mvc-frameworks-for-building-php-web-applications-2',
    #'advanced-wordpress-action-and-filter-hooks',
    #'building-and-securing-restful-apis-in-asp-dot-net-core',
    #'building-apis-with-loopback',
    #'building-restful-apis-in-laravel',
    #'node-js-design-patterns',
    #'wordpress-rest-api-building-an-interactive-web-app',
    #'windows-server-2016-deploying-containers',
    #'http-2-developing-for-performance',
    #'advanced-php',
    ##'advanced-php-debugging-techniques',
    #'learning-kubernetes',
    #'it-security-careers-and-certifications-first-steps',
    #'learning-sql-server-2017',
    #'advanced-java-programming',
    #'reactive-java-9',
    #'blockchain-beyond-the-basics',
    #'artificial-intelligence-foundations-thinking-machines',
    #'kotlin-essential-training',
    #'nail-your-java-interview',
    #'advanced-sql-for-data-scientists',
    #'machine-learning-ai-advanced-decision-trees',
    #'advanced-c-programming', - bulit
    #'cissp-cert-prep-2-asset-security-2',
    #'css-advanced-layouts-with-grid',
    #'advanced-animations-and-interactions-with-framer',
    #'mastering-puppet-for-large-infrastructures',
    #'react-securing-applications',
    #'python-advanced-design-patterns',
    #'architecting-big-data-applications-batch-mode-application-engineering',
    #'angular-maintaining-applications',
    #'mongodb-security',
	
	
	
    #'c-sharp-essential-training-2-flow-control-arrays-and-exception-handling',
    #'learning-redis',
    #'iot-foundations-operating-systems-fundamentals',
    #'c-sharp-essential-training-1-syntax-and-object-oriented-programming',
    #'learning-rest-apis',
    #'kubernetes-native-tools',
    #'optimizing-python-services',
    #'learning-java-3',
    #'c-sharp-for-unity-game-development',
    #'advanced-android-espresso-testing',
    #'planning-and-releasing-software-with-jira',
    #'c-plus-plus-design-patterns-creational',
    #'advanced-threading-in-c-sharp',
    #'multithreaded-programming-in-c-sharp',
    #'android-app-development-data-persistence-libraries',
    #'learning-sql-programming',
    #'react-js-essential-training',
    #'hadoop-for-data-science-tips-tricks-techniques',
    #'database-clinic-neo4j',
    #'learning-docker',
    #'api-testing-and-validation',
    #'learning-graphql',
    #'deploying-docker-to-aws',
    #'unity-5-3d-essential-training',
    #'docker-for-java-developers',
    #'intermediate-bot-framework-for-developers',
    #'docker-orchestration',
    #'unity-5-build-a-character-dialogue-system',
    #'learning-unity-2d-scripting',
    #'learning-unity-2d-sprites',
    #'building-a-match-3-game-with-unity', 
    #'build-a-real-time-strategy-game-with-unity-5', - bulit
    #'database-clinic-mongodb',
    #'android-development-concurrent-programming',
	
	
    #'building-a-web-interface-with-react-js',
    #'cert-prep-cisco-certified-entry-networking-technician-100-105',
    #'sql-tips-tricks-techniques',
    #'learning-redux',
    #'electronics-foundations-basic-circuits',
    #'building-and-deploying-a-full-stack-react-application',
    #'bootstrap-4-essential-training',
    #'machine-learning-ai-foundations-decision-trees',
    #'java-data-structures',
    #'cloud-computing-career-paths-and-certifications-first-steps',
    #'learning-python-with-pycharm',
    #'learning-relational-databases-2',
    #'ccna-security-210-260-cert-prep-4-secure-routing-and-switching',
	
	
    #'learning-linux-command-line',
    #'learning-flask',
    #'css-animation',
    #'cert-prep-comptia-security-plus-exam-sy0-501-the-basics',
    #'windows-server-2016-install-and-configure-active-directory',
    #'windows-server-2016-manage-monitor-and-maintain-servers',
    #'node-js-essential-training',
    #'building-material-design-apps-on-android-with-react-native',
    #'migrating-to-typescript-2',
    #'javascript-events',
    #'learning-ecmascript-6',
    #'react-building-large-apps',
    #'learning-composer-the-php-dependency-manager',
    #'react-managing-complex-interactions',
    #'node-js-deploying-applications',
    #'node-js-securing-restful-apis',
    #'express-essential-training',
	
	
	
    #'create-a-crm-mobile-application-with-react-native',
    #'building-complex-express-sites-with-redis-and-socket-io',
    #'learning-3d-graphics-on-the-web-with-three-js',
    #'asp-dot-net-core-test-driven-development',
    #'the-dom-in-javascript-jquery-angularjs-and-react',
    #'react-es6-es2016-and-beyond',
    #'asp-dot-net-core-security',
    #'responsive-css-workflow-with-sass-bourbon-and-susy',
    #'adobe-animate-cc-html5-canvas-and-webgl',
    #'building-apis-using-hapi-in-node-js',
    #'building-angular-and-asp-dot-net-core-apps-with-authentication',
    #'learning-web-components',
	
	
	#Andrei - 2 



    #'node-js-essential-training-2017',
    #'kubernetes-for-java-developers',
    #'learning-flask-2',
    #'linux-system-engineer-networking-and-ssh',
    #'introduction-to-5g',
    #'visual-studio-code-for-python-developers',
    #'test-automation-foundations',
    #'deep-learning-image-recognition',
    #'learning-c-plus-plus-3',
    #'graphql-essential-training',
    #'neural-networks-and-convolutional-neural-networks-essential-training',
    #'bootstrap-4-layouts-responsive-single-page-design',
    #'building-a-personal-portfolio-with-django',
    #'react-js-essential-training-3',
    #'android-development-essential-training-create-your-first-app-2',
    #'devops-foundations-microservices',
    #'internet-of-things-with-python-and-raspberry-pi',
    #'advanced-sql-for-query-tuning-and-performance-optimization',
    #'swift-5-essential-training',
    #'programming-foundations-web-security-2',
    #'applied-machine-learning-algorithms',
    #'node-js-microservices',
    #'learning-react-js-4',
    #'vue-js-essential-training-2',
    #'debugging-in-c-sharp',
    #'linux-system-engineer-database-servers-using-mariadb',
    #'linux-system-engineer-bash-shell-scripting-for-automation',
    #'programming-foundations-design-patterns-2',
    #'agile-software-development-remote-teams',
    #'learning-asp-dot-net-core-mvc',
    #'learning-web-audio-and-video',
    #'c-data-structures-pointers-and-file-systems',
    #'advanced-java-programming-2',
    #'raspberry-pi-weekly',
    #'kotlin-for-android-best-practices',
    #'deploying-exchange-server-2019',
    #'comptia-a-plus-220-1001-cert-prep-6-physical-networking',
    #'node-js-essential-training-3',
    #'comptia-a-plus-220-1002-cert-prep-2-implementation-considerations',
    #'linux-system-engineer-authentication-with-ldap-and-kerberos',
    #'javascript-patterns',
    #'get-ready-for-your-coding-interview',
    #'react-state-management',
    #'building-web-apis-with-asp-dot-net-web-api-2-2-2',
    #'vanilla-javascript-web-workers',
    #'python-for-data-science-tips-tricks-techniques',
    #'learning-jenkins',
    #'performing-complex-state-management-with-redux',
    #'css-design-systems-and-architectures',
    #'angular-workflows',
    
	
]